Faq page
HelpAPaw/WebApp-React pull request #15
Opened 2020-08-07 15:50 UTC by sanjana-1604

Code review for FAQ Page

2020-08-08 13:11 UTC, pnzrkmpfwgn requested changes
Code is fine and seems to work however in FAQPage_data.js "import React" seems to be unnecessary if there will be no code using jsx.

2020-08-14 22:34 UTC, nadunr submitted a review, later dismissed

2020-08-24 10:39 UTC, pnzrkmpfwgn approved these changes

2020-08-24 10:40 UTC, pnzrkmpfwgn submitted a review, later dismissed

2020-08-27 21:33 UTC, nadunr commented
approved

2020-10-01 17:11 UTC, Savzzy approved these changes

2020-10-06 07:40 UTC, BurningAXE approved these changes

2020-10-06 07:41 UTC, merged